### ISSUE TITLE
Portal? WTF?

### ISSUE THREAD

**Issue by em92** [em92/pickup-rating#7]
Running on_startup:
```
ERROR: Resetting connection with an active transaction <asyncpg.connection.Connection object at 0x7f8132885ea0>
ERROR: Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/eugene/quakelive-local-ratings/dev/venv/lib/python3.5/site-packages/uvicorn/lifespan/on.py", line 43, in main
    await app_instance(self.receive, self.send)
  File "/home/eugene/quakelive-local-ratings/dev/venv/lib/python3.5/site-packages/starlette/routing.py", line 478, in asgi
    await self.startup()
  File "/home/eugene/quakelive-local-ratings/dev/venv/lib/python3.5/site-packages/starlette/routing.py", line 461, in startup
    await handler()
  File "./qllr/__init__.py", line 37, in on_startup
    await submission.run_post_process(con)
  File "./qllr/submission.py", line 687, in run_post_process
    await _run_post_process(con)
  File "./qllr/submission.py", line 697, in _run_post_process
    async for match_id, gametype_id, timestamp in con.cursor(query):
  File "/home/eugene/quakelive-local-ratings/dev/venv/lib/python3.5/site-packages/asyncpg/cursor.py", line 182, in __anext__
    buffer = await self._exec(self._prefetch, self._timeout)
  File "/home/eugene/quakelive-local-ratings/dev/venv/lib/python3.5/site-packages/asyncpg/cursor.py", line 125, in _exec
    self._state, self._portal_name, n, True, timeout)
  File "asyncpg/protocol/protocol.pyx", line 291, in execute
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
asyncpg.exceptions.InvalidCursorNameError: портал "__asyncpg_portal_2__" не существует
ERROR: Application startup failed. Exiting.
```

**Comment by em92** [comment]
Fixed in https://github.com/em92/quakelive-local-ratings/commit/a166972fdd789bb567f88cd8dc270641292730bc
